main.py with photos
khoribz/KeyboardSimulation pull request #1
Opened 2021-04-04 20:56 UTC by khoribz

2021-04-11 08:53 UTC, corwinnn requested changes
а почему файлы капсом названы?

2021-04-11 08:53 UTC, corwinnn commented on DATA.py
> +    f = open('data.txt', 'w')
with open

2021-04-11 08:53 UTC, corwinnn commented on DATA.py
> +    f = open('data.txt', 'w')
и в следующих местах

2021-04-11 08:53 UTC, corwinnn commented on FUNCTIONS.py
> +# Проверка вводимого символа на совпадение с правильным
документацию лучше писать после def

2021-04-11 08:53 UTC, corwinnn commented on FUNCTIONS.py
> +            return "True"
магическая константа

2021-04-11 08:53 UTC, corwinnn commented on GAME.py
> +        place_for_input_box_y = GLOBAL.input_box.y + 5
тоже магическая константа, и в других местах

2021-04-19 19:30 UTC, corwinnn requested changes

2021-04-19 19:30 UTC, corwinnn commented on README.md
> +Для старта нужно нажать на окошко "Нажмите, чтобы ввести текст".
так и задумано, что весь текст жирный?

2021-04-19 19:30 UTC, corwinnn commented on data.py
> +    arr_texts = ['texts/1.txt', 'texts/2.txt', 'texts/3.txt', 'texts/4.txt', 'texts/5.txt',
давай в одну строку циклом

2021-04-19 19:30 UTC, corwinnn commented on data.py
> +        words = words[:-1]
нужен комментарий, непонятно, что происходит

2021-04-19 19:30 UTC, corwinnn commented on functions.py
> +        if event == text[cnt]:
`return event == text[cnt]`

2021-04-19 19:30 UTC, corwinnn commented on game.py
> +        print_file.print_text( text_for_inscription, color.BLACK, place_for_inscription, font_size_for_inscription)
лишний пробел после скобки

2021-04-19 19:30 UTC, corwinnn commented on game.py
> +                if global_file.input_box.x <= pg.mouse.get_pos()[0] <= global_file.input_box.x + global_file.input_box.w\
пробел перед \

2021-04-19 19:30 UTC, corwinnn commented on print_file.py
> +    location_for_input_box_off = global_file.display_width / 3  # какой отступ текста от края окна вывода, если клавиатура неактивна
магическая константа

2021-04-19 19:30 UTC, corwinnn commented on print_file.py
> +        global_file.display.blit(input_text_image, (location_for_input_box_off, global_file.input_box.y + top_indent))
тут можно написать 
```
box = box_on if is_active else box_off
blit(img, (box, ...)
```

2021-04-23 11:57 UTC, khoribz commented on README.md
> +Для старта нужно нажать на окошко "Нажмите, чтобы ввести текст".
Да, но могу сделать обычным, если нужно

2021-04-23 11:57 UTC, khoribz commented on data.py
> +    arr_texts = ['texts/1.txt', 'texts/2.txt', 'texts/3.txt', 'texts/4.txt', 'texts/5.txt',
сделал

2021-04-23 11:59 UTC, khoribz commented on data.py
> +        words = words[:-1]
убрал words = words[:-1]. Проблема была в том, что в моих текстах был перевод на новую строку, что некорректно отображалось в окне. Исправил это, убрав в текстах этот перевод

2021-04-23 14:05 UTC, corwinnn requested changes

2021-04-23 14:05 UTC, corwinnn commented on data.py
> +        data_file.write('mistakes:\n' + str(mistakes))
используй fstrings

2021-04-23 14:05 UTC, corwinnn commented on data.py
> +        speed = data_file.read().split('\n')[1]
магическая константа

2021-04-23 14:05 UTC, corwinnn commented on data.py
> +        mistakes = data_file.read().split('\n')[3]
магическая константа

2021-04-23 14:05 UTC, corwinnn commented on data.py
> +    arr_texts = ['texts/' + str(i) + '.txt' for i in range(num_of_first_file, number_files)]
fstring

2021-04-23 14:05 UTC, corwinnn commented on print_file.py
> +    print_text("---  " + str(len(text)), color.BLACK, (global_file.text_box.x + left_indent_for_data,
fstring тут и дальше

2021-04-23 14:05 UTC, corwinnn commented on print_file.py
> +            break
непонятно, что происходит

2021-04-24 08:01 UTC, corwinnn requested changes

2021-04-24 08:01 UTC, corwinnn commented on data.py
> +        speed = data_file.read().split('\n')[num_of_speed_line]
нет ли метода, который делает сплит сам?

2021-04-24 08:01 UTC, corwinnn commented on print_file.py
> +    list_of_words = text.split(" ")  # разделяем текст на слова и кладем в лист
а какой дефолтный параметр сплит?

2021-04-24 09:02 UTC, khoribz commented on data.py
> +        speed = data_file.read().split('\n')[num_of_speed_line]
Можно использовать readlines(), но тогда в каждой строке последним символом будет '\n', от которого нужно будет избавляться в строке speed. С помощью сплита выходит лаконичнее)

2021-04-24 09:02 UTC, khoribz commented on print_file.py
> +    list_of_words = text.split(" ")  # разделяем текст на слова и кладем в лист
Пробел, нужно написать list_of_words = text.split()

2021-05-22 18:59 UTC, merged